apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
      app: projapp
    name: projapp

  spec:
    replicas: 4
    selector:
      matchLabels:
        app: projapp

    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: projapp

      spec:
        containers:

        - image: mohamedsamir759/httpd

          name: projapp

        - containerport: "8080"


